### PR TITLE
Added support for Carthage

### PR DESCRIPTION
**Pull request by hkellaway**
* Added support for Carthage
* Moved tests from Example project to framework project

### CODE REVIEW

**Comment by hkellaway** [comment]
You'll see a few new things:

* New framework project at root called `Caishen.xcodeproj`
* New folder at root called `CaishenTests`

The framework project is because that's what Carthage users use to build off of.

The CaishenTests folder is because it's not intuitive to have tests place alongside an Example project, and many wouldn't know to find them there. Also, having them in the framework project will remind you to open up the framework project and run tests when you're looking to submit a new version to Cocoapods, so you don't forget to keep that project up-to-date.

**Comment by DannyVancura** [comment]
👍

**Comment by Haud** [comment]
Is there any reason we would do this instead of creating a shared scheme that outputs a framework?

**Comment by hkellaway** [comment]
Not sure how to do that. Is there a benefit to that approach?

**Comment by Haud** [comment]
Just a little weird that we're now going to have two `Caishen.xcodeproj` files in our framework, each of which does something different.

**Comment by hkellaway** [comment]
ah, i see. i usually name my Example projects something different - like `CaishenExample`, so i've never thought of it as odd

**Comment by DannyVancura** [comment]
I just pushed a PR on top of this, to rename the example project.
Imo, renaming this certainly makes sense. Otherwise: :+1:

**Comment by hkellaway** [comment]
whomever else is to approve this ( @Haud @ThibaultKlein ?) - can you take a look ?

**Comment by ThibaultKlein** [comment]
Worked for me. 👍

**Pull request merged**
