### PR TITLE
Refactored card expiry to be a struct with a raw value as a date

### PR DESCRIPTION
**Pull request by Haud**

### CODE REVIEW

**Comment by DannyVancura** [comment]
Looks great! Currently the tests aren't working with this implementation though.

**Comment by Haud** [comment]
Oh whoops, forgot to check them. Let me do that and take care of Thibautl's issue request.

**Comment by Haud** [comment]
@DannyVancura fixed the tests.

**Comment by ppatriotis** [comment]
@Haud there's conflicts...

**Comment by Haud** [comment]
@prolificphotis fixed. Going to merge.

**Pull request merged**
