### PR TITLE
Added customizable insets for image & accessory button

### PR DESCRIPTION
**Pull request by DannyVancura**
Added view constraints and IBDesignable properties to provide insets around the image view and accessory button.

Addresses [issue #12](https://github.com/prolificinteractive/Caishen/issues/12)

### CODE REVIEW

**Comment by Haud** [comment]
Looks good. @MichaelCampbell can you test this to see if it fixes your issue?

**Comment by Haud** [comment]
Still going to wait for Campbell to confirm that this is working as intended. As far as I'm concerned, this is not a blocker for release.

**Comment by MichaelCampbell** [comment]
This works well. :+1:

**Comment by Haud** [comment]
@DannyVancura conrflakes

**Comment by DannyVancura** [comment]
Resolved 👍

**Comment by MichaelCampbell** [comment]
still good to go

**Pull request merged**
