### PR TITLE
Fixed a bug where pressing the buy now button would freeze the UI

### PR DESCRIPTION
**Pull request by JamesJSY**
@DannyVancura

### CODE REVIEW

**Comment by DannyVancura** [comment]
Unfortunately, the problem still seems to remain for me

**Comment by Haud** [comment]
What's the status on this @JamesJSY @DannyVancura

**Comment by JamesJSY** [comment]
@Haud The issue should be fixed in the updated build. Still needs more tests to confirm that.

**Comment by DannyVancura** [comment]
I pushed a change to remove the second blur view on this. However, it seems to fix the problem! The only visible change on this PR is that the blur view is no longer extended below the status bar.
:+1:

**Comment by JamesJSY** [comment]
@DannyVancura Pushed a new commit to extend blur view to cover status bar

**Comment by DannyVancura** [comment]
👍

**Pull request merged**
